markdown: rdiscount
pygments: true
permalink: /blog/:title
auto: true
rdiscount:
  extensions: [smart]
lsi: true
exclude: ['README.markdown', 'README_FOR_COLLABORATORS.markdown', 'Gemfile.lock', 'Gemfile']
production: false
paginate: true 
 