name: Portfolio Site by Rashna Razdan
markdown: kramdown
pygments: true
auto: true
comments: true
paginate: 20
safe: false
analytics :
  provider : google
  google : 
      tracking_id : 'UA-43164045-1'
  getclicky :
    site_id :


  